// Development mock.
//
// Exists so the queue, approval flow and UI states can be exercised without
// developer credentials for five platforms. It is deliberately impossible to
// mistake for a real connection: it only registers when CHORUS_DEV_MOCK=1, its
// label says so, every account it creates carries isMock, and "sending" writes
// to a local log and returns an id prefixed `mock-`. Nothing leaves the machine.

const crypto = require('crypto');
const { SocialProvider, CAPABILITY } = require('../core/provider');
const { supported } = require('../core/capabilities');
const registry = require('../core/registry');
const accounts = require('../core/accounts');

const ENABLED = process.env.CHORUS_DEV_MOCK === '1';

class MockProvider extends SocialProvider {
  constructor() {
    super({
      id: 'mock',
      label: 'Development Mock',
      docs: 'https://github.com/BofStudios/chorus',
      notes:
        'This is not a real connected account. Nothing is sent anywhere. It exists only so the approval queue and sending pipeline can be tested without live credentials.',
      credentials: { required: [] },
      oauth: { scopes: ['mock.profile', 'mock.send'] },
      limits: { perMinute: 600, burst: 50 },
      capabilities: {
        [CAPABILITY.PROFILE]: supported(),
        [CAPABILITY.SEARCH]: supported(),
        [CAPABILITY.SEND_MESSAGES]: supported()
      }
    });
    this.sent = [];
  }

  isConfigured() {
    return true;
  }

  /** No OAuth round trip — it creates a flagged local account immediately. */
  beginConnection() {
    const account = accounts.upsert(
      {
        provider: this.id,
        providerAccountId: `mock-${crypto.randomBytes(4).toString('hex')}`,
        username: '@dev-mock',
        displayName: 'Development Mock',
        scopes: this.oauth.scopes,
        metadata: { mock: true },
        isMock: true
      },
      { accessToken: 'mock-token', refreshToken: '', expiresAt: null }
    );
    return { mock: true, accountId: account.id, url: null };
  }

  async getAccount() {
    return {
      id: `mock-${crypto.randomBytes(4).toString('hex')}`,
      username: '@dev-mock',
      displayName: 'Development Mock',
      avatar: '',
      metadata: { mock: true }
    };
  }

  async _getProfile(account, { username }) {
    return {
      platformUserId: `mock-${username}`,
      username: `@${String(username || 'someone').replace(/^@/, '')}`,
      displayName: 'Mock Profile',
      bio: 'Generated by the development mock provider.',
      profileUrl: '',
      isMock: true
    };
  }

  async _search(account, { query, limit = 5 }) {
    return Array.from({ length: Math.min(limit, 5) }, (_, index) => ({
      platform: 'mock',
      platformUserId: `mock-${index}`,
      username: `@mock_${index}`,
      displayName: `Mock Prospect ${index + 1}`,
      bio: `Development fixture for "${query}".`,
      profileUrl: '',
      isMock: true,
      evidence: { type: 'mock', text: 'Not a real result.' }
    }));
  }

  async _createMessage(account, { recipient, body }) {
    return { provider: this.id, to: recipient, text: body, isMock: true };
  }

  async _sendMessage(account, payload) {
    this.sent.push({ to: payload.to, at: Date.now() });
    return {
      providerMessageId: `mock-${crypto.randomBytes(6).toString('hex')}`,
      isMock: true,
      delivered: false,
      note: 'Recorded locally by the development mock. Nothing was transmitted.'
    };
  }
}

module.exports = ENABLED ? registry.register(new MockProvider()) : null;
